---
- name: Deploy Docker Compose stack to Docker
  hosts: '{{kitsune_target|default("all")}}'
  tasks:
    - name: Deploy Docker Compose stack
      community.docker.docker_compose_v2:
        definition:
          "{{ lookup('ansible.builtin.template', kitsune_docker_compose_stack_docker_compose_file_src_template_file) |
          from_yaml }}"
        project_name: "{{ kitsune_docker_compose_stack_docker_compose_project_name }}"
        state: present
      tags:
        - docker_compose_stack
